version: '3.9'
services:
 py3:
   build:
     context: .
     dockerfile: ./Dockerfile
#volumes must be abspath 
   volumes:
     - "/home/tomoki/:/home/tomoki/py3/working"
     - ".:/home/tomoki/py3/working"
     - "/usr/lib/python3/dist-packages:/home/tomoki/py3/working"
  
   ports:
     - "8888:8888"

   tty: true

   env_file: my_env_file.env

   command: jupyter notebook --no-browser --ip=0.0.0.0 --notebook-dir=. --allow-root --NorebookApp.token=''

   deploy:
    resources:
     reservations:
      devices:
       - driver: nvidia
         count: all
         capabilities: [gpu]

