version: '3.9'
services:
 py3:
   user: $UID:$GID
   build:
     context: .
     dockerfile: ./Dockerfile
     args:
       UID: $UID
       GID: $GID
       UNAME: $UNAME

#volumes must be abspath 
   volumes:
     - "/home/tomoki/py3/data:/workspace/working"
  
   ports:
     - "8888:8888"

   tty: true

   env_file: my_env_file.env

   command: jupyter notebook --no-browser --ip=0.0.0.0 --notebook-dir=. --allow-root --NorebookApp.token='' 

   deploy:
    resources:
     reservations:
      devices:
       - driver: nvidia
         count: all
         capabilities: [gpu]

